server:
  port: 8083

spring:
  application:
    name: ms-groupes
  datasource:
    url: jdbc:postgresql://localhost:5432/njangi?currentSchema=groupes
    username: njangi
    password: njangi_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: groupes
  flyway:
    enabled: true
    schemas: groupes
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ms-groupes-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.njangi.*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    com.njangi: DEBUG
