server:
  port: 8001

spring:
  application:
    name: ms-auth
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:njangi}?currentSchema=auth
    username: ${DB_USER:njangi}
    password: ${DB_PASS:njangi_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
  flyway:
    enabled: true
    schemas: auth
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ms-auth-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

njangi:
  jwt:
    # Clé secrète de 256 bits minimum pour signature HMAC-SHA256
    secret: ${JWT_SECRET:NjangiPlateformeSecreteTresLonguePourHmacSha256Signature2026!}
    # 24 heures en millisecondes = 86400000
    expiration: ${JWT_EXPIRATION:86400000}
  otp:
    expiration-minutes: 5

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true

logging:
  level:
    com.njangi.auth: DEBUG
    org.springframework.security: INFO
