server:
  port: 8081

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:njangi}?currentSchema=auth
    username: ${DB_USER:njangi}
    password: ${DB_PASS:njangi}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
  flyway:
    schemas: auth
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
