server:
  port: 8085

spring:
  application:
    name: ms-cotisations

  datasource:
    url: jdbc:postgresql://localhost:5432/njangi?currentSchema=cotisations
    username: njangi
    password: njangi_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: cotisations
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    schemas: cotisations
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ms-cotisations-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/njangi

logging:
  level:
    com.njangi.cotisations: DEBUG
    org.springframework.security: INFO
